export const notesTypes = {
  ADD_NEW_NOTE_START: "ADD_NEW_NOTE_START",
  FETCH_NOTES_START: "FETCH_NOTES_START",
  SET_NOTES: "SET_NOTES",
  DELETE_NOTES_START: "DELETE_NOTES_START",
  ADD_NOTE_CONTENT_START: "ADD_NOTE_CONTENT_START",
  ADD_HEADER_IMG_START: "ADD_HEADER_IMG_START",
  CURRENT_DOCUMENT: "CURRENT_DOCUMENT",
};

export default notesTypes;
